env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
  import/resolver:
    typescript: true
    node: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:react-redux/recommended
  - plugin:jsx-a11y/recommended
  - plugin:unicorn/recommended
  - plugin:prettier/recommended
plugins:
  - react
  - react-refresh
  - simple-import-sort
rules:
  react-refresh/only-export-components: warn
  simple-import-sort/imports: error
  simple-import-sort/exports: error
overrides:
  - files: '**/*.ts?(x)'
    rules:
      react/prop-types: off
